### ISSUE TITLE
"make -j8"error

### ISSUE THREAD

**Issue by zhangguanghui1** [lawy623/SVS#4]
When I run ”make -j8"，
.......
CXX src/caffe/layers/generate_augmentation_parameters_layer.cpp
src/caffe/util/util_img.cpp:709:33: error: redeclaration of ‘template<class Dtype> cv::Mat caffe::BlobToGrayImage(const caffe::Blob<Dtype>*, int, int, Dtype)’ may not have default arguments [-fpermissive]
   const Dtype scale = Dtype(1.0)) {
                                 ^
Makefile:596: recipe for target '.build_release/src/caffe/util/util_img.o' failed
make: *** [.build_release/src/caffe/util/util_img.o] Error 1
make: *** Waiting for unfinished jobs....

Thank you very much!

**Comment by TrackingBird** [comment]
@zhangguanghui1 Dear si, have you solve this issue?I also meet this error. Can you give me some suggestions? Thanks.

**Comment by qianwangn** [comment]
+1

**Comment by yanqi1811** [comment]
+1

**Comment by junfengcao** [comment]
I met this error too . 
Have you solved this error?
